function phoenixA4Cadence(movement){return movement.cadence.map(phase=>`${phase.duration} SEC ${phase.action}`).join(' / ');}
function openPhoenixA4Poster(movementId){
  const movement=getMovement(movementId);if(!movement)return;
  let viewer=document.getElementById('phoenixA4Viewer');
  if(!viewer){viewer=document.createElement('div');viewer.id='phoenixA4Viewer';viewer.className='phoenix-a4-viewer';document.body.appendChild(viewer);}
  const alternate=!movement.assets.heroIncludesAlternateView&&movement.assets.alternateView?`<figure class="phoenix-a4-alternate"><img src="${movement.assets.alternateView}" alt="${movement.assets.alternateViewLabel}"><figcaption>${movement.assets.alternateViewLabel}</figcaption></figure>`:'';
  viewer.innerHTML=`<button class="phoenix-a4-close" onclick="closePhoenixA4Poster()">Fermer</button><article class="phoenix-a4-poster" data-movement-id="${movement.id}"><header class="phoenix-a4-header"><div class="phoenix-a4-bird">✦</div><div class="phoenix-a4-brand">PHOENIX</div><div class="phoenix-a4-edition">PHOENIX 03</div><h1>${movement.posterNumber}. ${movement.name.toUpperCase()}</h1><p><span></span>${movement.subtitle}<span></span></p></header><div class="phoenix-a4-layout"><section class="phoenix-a4-visual"><img src="${movement.assets.hero}" alt="${movement.name} — illustration technique">${alternate}</section><aside class="phoenix-a4-copy"><section><h2><b>◎</b> Objectif</h2><p data-shared-field="objective">${movement.objective}</p></section><section><h2><b>▣</b> Comment faire</h2><ol data-shared-field="instructions">${movement.instructions.map(item=>`<li>${item}</li>`).join('')}</ol></section><section><h2><span class="phoenix-metronome"><i></i></span> Cadence</h2><p data-shared-field="cadence">${movement.cadence.map(phase=>`${phase.duration} sec pour ${phase.action.toLowerCase()}`).join(' — ')}</p></section><section><h2><b>◷</b> Départ</h2><p data-shared-field="volume">${movement.volume}</p></section><section class="phoenix-a4-avoid"><h2><b>△</b> À éviter</h2><ul data-shared-field="avoid">${movement.avoid.map(item=>`<li>${item}</li>`).join('')}</ul></section></aside><section class="phoenix-a4-sequence"><div>CADENCE : ${phoenixA4Cadence(movement)}</div><img src="${movement.assets.sequence}" alt="Séquence du mouvement"></section></div><footer><span></span>PETITS EFFORTS QUOTIDIENS, TRANSFORMATIONS DURABLES.<span></span></footer></article>`;
  viewer.hidden=false;viewer.scrollTop=0;document.body.classList.add('phoenix-a4-open');
}
function closePhoenixA4Poster(){const viewer=document.getElementById('phoenixA4Viewer');if(viewer)viewer.hidden=true;document.body.classList.remove('phoenix-a4-open');}
